language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - rbx-2.0.0
  - rbx-2.1.1
gemfiles:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2.0.0
    - rvm: rbx-head
script: rspec
